app/appChat/models.py
from db import db

class UserModel(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80))
    password = db.Column(db.String(80))

    def __init__(self, name, password):
        self.name = name
        self.password = password

    def save_to_db(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def find_by_username(cls, name):
        return cls.query.filter_by(name=name).first()

    @classmethod
    def find_by_id(cls, _id):
        return cls.query.filter_by(id=_id).first()


class Message(db.Model):
    __tablename__ = 'messages'

    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text)
    created_at = db.Column(db.DateTime)  
    name_id=db.Column(db.Integer, db.ForeignKey('users.id'))
    origin = db.relationship('UserModel')
    

    def __init__(self, content, created_at, name_id):
        self.content = content
        self.created_at =created_at
        self.name_id = name_id

    def save_to_db(self):
        db.session.add(self)
        db.session.commit()

    class Meta:
        ordering = ['-created_at']
    
    @classmethod
    def find_by_name_id(cls, _name_id):
        return cls.query.filter_by(name_id=_name_id).all()

app/appChat/forms.py
from flask_wtf import Form
from wtforms.fields import StringField, PasswordField, SubmitField
from wtforms.validators import Required, EqualTo


class LoginForm(Form):   
    name = StringField('Name', validators=[Required()])    
    password= PasswordField('PassWord', validators=[Required()])
    submit = SubmitField('Login in')
class RegisterForm(Form):
    name = StringField('Name', validators=[Required()])
    password = PasswordField('PassWord', validators=[Required(), EqualTo('confirm', message='Passwords must match')])
    confirm = PasswordField('Confirm PassWord', validators=[Required()])
    submit = SubmitField('Register')
class ChatRoomsForm(Form):    
    chatroom = StringField('Room', validators=[Required()])
    submit = SubmitField('Enter to ChatRoom')

app/forms.py
from flask_wtf import Form
from wtforms.fields import StringField, PasswordField, SubmitField
from wtforms.validators import Required


class LoginForm(Form):   
    name = StringField('Name', validators=[Required()])
    chatroom = StringField('Room', validators=[Required()])
    password= PasswordField('PassWord', validators=[Required()])
    submit = SubmitField('Enter Chatroom')

app/__init__.py
from flask import Flask, session, redirect, url_for, render_template, request, flash
from flask_socketio import SocketIO
from functools import wraps

socketio = SocketIO()

def login_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return f(*args, **kwargs)
        else:
            flash("You need to login first")
            return redirect(url_for('.login'))

    return wrap

def date_of(timestamp):
    if timestamp is not None:
        return timestamp.now().strftime('%Y-%m-%d %H:%M:%S')		

def create_app(debug=False):
    """Create an application."""
    app = Flask(__name__)
    app.debug = debug
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///data.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['SECRET_KEY'] = 'og8DGknlZ-AXdHwT5DOiFoFs'

    from .appChat import main as main_blueprint
    app.register_blueprint(main_blueprint)

    socketio.init_app(app)    
    return app

app/appChat/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, events

app/appChat/views.py
from flask import session, redirect, url_for, render_template, request, flash
from . import main
from .forms import LoginForm, RegisterForm, ChatRoomsForm
from .models import UserModel, Message
from werkzeug.security import safe_str_cmp
from app import login_required


@main.route('/', methods=['GET', 'POST'])
def login():
    """Login form to enter a room."""
    error=""
    form = LoginForm()
    if form.validate_on_submit():
        name = form.name.data
        password = form.password.data
        user = UserModel.find_by_username(name)
        if user and safe_str_cmp(user.password, password):
            session['logged_in'] = True
            session['name'] = name
            session['id']=user.id
            print(session['id'])
            return redirect(url_for('.chatroom'))
        else:
            flash( "Invalid credentials, try again.")
    elif request.method == 'GET':
        form.name.data = session.get('name', '')        
    return render_template('login.html', form=form, error=error)

@main.route('/register/', methods=['GET', 'POST'])
def register():
    """Register form to enter a room."""
    form = RegisterForm()
    if form.validate_on_submit():
        name = form.name.data
        password = form.password.data
        if UserModel.find_by_username(name):
            flash("A user with that username already exists")
            return render_template('register.html',form=form)
        user = UserModel(name, password)
        user.save_to_db()
        session['logged_in'] = True
        session['name'] = name
        session['id']=user.id        
        flash("User created successfully.")
        return redirect(url_for('.chatroom'))
    elif request.method == 'GET':
        form.name.data = session.get('name', '')        
    return render_template('register.html',form=form)

@main.route('/chatroom/', methods=['GET', 'POST'])
@login_required
def chatroom():
    form = ChatRoomsForm() 
    if form.validate_on_submit():
        session['chatroom'] = form.chatroom.data
        return redirect(url_for('.chat'))    
    return render_template('chatroom.html', form=form)


@main.route('/chat')
@login_required
def chat():   
    name = session.get('name', '')
    chatroom = session.get('chatroom', '')
    if name == '' or chatroom == '':
        return redirect(url_for('.login'))
    return render_template('chat.html', name=name, chatroom=chatroom)

@main.route('/messages/')
@login_required
def messages():
    name = session.get('name', '')
    chatroom = session.get('chatroom', '')   
    messages=Message.find_by_name_id(session.get('id')) 
    messages=messages[0:49]   
    return render_template('messages.html', messages=messages, name=name, chatroom=chatroom)


@main.route('/logout/')
@login_required
def logout():   
    session.clear()
    flash("You have been logged out!")    
    return redirect(url_for('.login'))
    

app/templates/chat.html
<html>
    <head>
        <title>Chat Application: {{ chatroom }}</title>
        <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>
        <script type="text/javascript" charset="utf-8">
            var socket;
            $(document).ready(function(){
                socket = io.connect('http://' + document.domain + ':' + location.port + '/chat');
                socket.on('connect', function() {
                    socket.emit('joined', {});
                });
                socket.on('status', function(data) {
                    $('#chat').val($('#chat').val() + '<' + data.msg + '>\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                socket.on('message', function(data) {
                    $('#chat').val($('#chat').val() + data.msg + '\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                $('#text').keypress(function(e) {
                    var code = e.keyCode || e.which;
                    if (code == 13) {
                        text = $('#text').val();
                        $('#text').val('');
                        socket.emit('text', {msg: text});
                    }
                });
            });
            function leave_room() {
                socket.emit('left', {}, function() {
                    socket.disconnect();

                    // go back to the login page
                    window.location.href = "{{ url_for('main.chatroom') }}";
                });
            }
        </script>
    </head>
    <body>
        <h1>Chat Application: {{ chatroom }}</h1>
        <textarea id="chat" cols="80" rows="20"></textarea><br><br>
        <input id="text" size="80" placeholder="Enter your message here"><br><br>        
        <a href="#" onclick="leave_room();"><button type="button" class="btn btn-primary" aria-label="Left Align" >
		  <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Leave this ChatRoom
		</button></a>
        <a href="/logout/"><button type="button" class="btn btn-primary" aria-label="Left Align" >
		  <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Log Out
		</button></a>
        <a href="/messages/"><button type="button" class="btn btn-primary" aria-label="Left Align" >
		  <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Message History
		</button></a>
    </body>
</html>

app/templates/chatroom.html
<html>
    <head>
        <title>Chat Application</title>
    </head>
    <body>
        <h1>Chat</h1>
        <form method="POST">
            {{ form.hidden_tag() }}       
            {{ form.chatroom.label }}: {{ form.chatroom() }} {% for error in form.chatroom.errors %}{{ error }}{% endfor %}<br>
            {{ form.submit() }}
        </form>        
    </body>
</html>

app/templates/index.html
<html>
    <head>
        <title>Chat Application</title>
    </head>
    <body>
        <h1>Chat</h1>
        <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.name.label }}: {{ form.name() }} {% for error in form.name.errors %}{{ error }}{% endfor %}<br>
            {{ form.chatroom.label }}: {{ form.chatroom() }} {% for error in form.chatroom.errors %}{{ error }}{% endfor %}<br>
            {{ form.submit() }}
        </form>
    </body>
</html>

app/templates/login.html
<html>
    <head>
        <title>Chat Application</title>
    </head>
    <body>
        <h1>Chat</h1>
        <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.name.label }}: {{ form.name() }} {% for error in form.name.errors %}{{ error }}{% endfor %}<br>
            {{ form.password.label }}: {{ form.password() }} {% for error in form.password.errors %}{{ error }}{% endfor %}<br>
            {{ form.submit() }}
        </form>
        <a href="/register/"><button type="button" class="btn btn-primary" aria-label="Left Align" >
		  <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Register
		</button></a>
    </body>
</html>

app/templates/messages.html
<html>
    <head>
        <title>Chat Application</title>
    </head>
    <body>
        <h1>Message History of: {{ name }}</h1>
        <div id="history">
   	        {% for message in messages %}
   	            {{message.content}} <br>
            	----{{message.created_at}}---- <br>
   	        
   	        {% endfor %}
        </div>
        </form> 
        <a href="/chat"><button type="button" class="btn btn-primary" aria-label="Left Align" >
		  <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Back to Chat
		</button></a>       
    </body>
</html>

app/templates/register.html
<html>
    <head>
        <title>Chat Application</title>
    </head>
    <body>
        <h1>Chat</h1>
        <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.name.label }}: {{ form.name() }} {% for error in form.name.errors %}{{ error }}{% endfor %}<br>
            {{ form.password.label }}: {{ form.password() }} {% for error in form.password.errors %}{{ error }}{% endfor %}<br>
            {{ form.confirm.label }}: {{ form.confirm() }} {% for error in form.confirm.errors %}{{ error }}{% endfor %}<br>
            {{ form.submit() }}
        </form>
    </body>
</html>